import Foundation
import Testing
@testable import AxonCore

@Test func semanticNamesDeriveFromSerializedSnapshotDeterministically() throws {
    let fixture = URL(fileURLWithPath: #filePath).deletingLastPathComponent().appending(path: "Fixtures/semantic-names.json")
    let json = try JSONDecoder().decode(JSONValue.self, from: Data(contentsOf: fixture))
    let first = SemanticNameDeriver.derive(from: json)
    let second = SemanticNameDeriver.derive(from: json)

    #expect(first == second)
    #expect(first.elements.first(where: { $0.sourceIndex == 3 })?.name == "menu/file/new-note")
    #expect(first.elements.first(where: { $0.sourceIndex == 6 })?.name == "notes/folders/add")
    #expect(first.elements.first(where: { $0.sourceIndex == 8 })?.name == "notes/editor/done-button")
    #expect(first.elements.first(where: { $0.sourceIndex == 9 })?.name == "notes/editor/done-text")
    #expect(first.elements.first(where: { $0.sourceIndex == 10 })?.name == "notes/editor/share-1")
    #expect(first.elements.first(where: { $0.sourceIndex == 11 })?.name == "notes/editor/share-2")
    #expect(first.summary.collisionFreeCount == first.summary.eligibleElementCount - 2)
}

@Test func semanticNamesRejectFrameworkIdentifiersAndBoundSlugs() {
    #expect(SemanticNameDeriver.isAutogeneratedIdentifier("_NS:341"))
    #expect(!SemanticNameDeriver.isAutogeneratedIdentifier("compose-button"))
    #expect(SemanticNameDeriver.slug("Résumé / Open…") == "resume-open")
    #expect(SemanticNameDeriver.slug("A very long human readable title", maximumLength: 12) == "a-very-long")
}

@Test func semanticNameStabilityIgnoresGeometryAndSnapshotHandles() throws {
    func snapshot(id: String, x: Int) throws -> JSONValue {
        let raw = #"{"id":"\#(id)","windows":[{"index":\#(x),"handle":"\#(id):0","role":"AXWindow","title":"Main","frame":{"x":\#(x)},"children":[{"index":\#(x + 1),"handle":"\#(id):1","role":"AXButton","title":"Save"}]}]}"#
        return try JSONDecoder().decode(JSONValue.self, from: Data(raw.utf8))
    }
    let first = SemanticNameDeriver.derive(from: try snapshot(id: "s1", x: 0))
    let moved = SemanticNameDeriver.derive(from: try snapshot(id: "s2", x: 400))
    let result = SemanticNameDeriver.stability(from: first, to: moved)

    #expect(result.comparableElements == 2)
    #expect(result.stableNames == 2)
    #expect(result.fraction == 1)
}