"""Generated by sdk/generate.ts from schema/tool-surface-v1.json. Do not edit."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Final, Literal, NotRequired, Protocol, Required, TypeAlias, TypedDict

SCHEMA_PRODUCT_VERSION: Final = "0.3.6"

# Per-tool platform availability, keyed by socket method then by daemon facade.
AVAILABILITY: Final[Mapping[str, Mapping[str, bool]]] = {
    "capture_screen": {"linux": True, "mac": False, "swift": False, "windows": False},
    "look": {"linux": True, "mac": True, "swift": True, "windows": True},
    "navigate": {"linux": False, "mac": False, "swift": True, "windows": False},
    "windows": {"linux": False, "mac": False, "swift": True, "windows": False},
    "tabs": {"linux": False, "mac": False, "swift": True, "windows": False},
    "find": {"linux": True, "mac": True, "swift": True, "windows": True},
    "wait_for_value": {"linux": True, "mac": True, "swift": True, "windows": True},
    "wait_for_stability": {"linux": True, "mac": True, "swift": True, "windows": True},
    "permit": {"linux": False, "mac": False, "swift": True, "windows": False},
    "run": {"linux": True, "mac": True, "swift": True, "windows": True},
    "save": {"linux": True, "mac": True, "swift": True, "windows": True},
    "click": {"linux": True, "mac": True, "swift": True, "windows": True},
    "type": {"linux": True, "mac": True, "swift": True, "windows": True},
    "keyboard": {"linux": True, "mac": True, "swift": True, "windows": True},
    "scroll": {"linux": False, "mac": True, "swift": True, "windows": True},
    "drag": {"linux": False, "mac": False, "swift": True, "windows": False},
    "invoke": {"linux": True, "mac": True, "swift": True, "windows": True},
}


class CaptureScreenParams(TypedDict, total=False):
    """Capture the user-authorized desktop ScreenCast source. The selected source is not associated with any application."""

    # Ignore any stored restore token and request fresh portal authorization. The token is replaced only after ScreenCast Start succeeds.
    reauthorize: NotRequired[bool]


class LookParamsTarget(TypedDict, total=False):
    """Semantic element target object with required app and name fields. Run look first to observe canonical names."""

    # Bundle id, pid, app name, or partial app name.
    app: Required[str]
    # Semantic element name returned by look.
    name: Required[str]


class LookParams(TypedDict, total=False):
    """Observe Axon's current surface: no app lists apps, app captures state, a semantic target pages children, and since returns a change check. An observation whose note is no-windows means the application is running with no window open; the tree still holds its menu bar, so open one through the application's own File > New Window item before acting."""

    # For no-target app lists, include all running processes. For direct semantic child requests, include all direct children.
    all: NotRequired[bool]
    # Bundle id, pid, app name, or partial app name. Omit with target to list apps.
    app: NotRequired[str]
    # Nonnegative initial child depth for app observations. Use 0 to retain top-level windows only and page children by semantic target.
    childDepth: NotRequired[int]
    # Nonnegative maximum tree depth to display for app observations, with windows at depth 0.
    depth: NotRequired[int]
    # For semantic targets, return only direct children without recursively capturing descendants.
    direct: NotRequired[bool]
    # Output format: observation or debug. Defaults to observation; use debug only when diagnosing Axon internals.
    format: NotRequired[Literal["observation", "debug"]]
    # Include frames in observation output. Defaults to false.
    frames: NotRequired[bool]
    # Nonnegative maximum children for a semantic target. Defaults to Axon's sibling page size; 0 requests all remaining children when all is true.
    limit: NotRequired[int]
    # Zero-based, nonnegative child offset for a semantic target. Defaults to 0.
    offset: NotRequired[int]
    # OCR visible text from the app window screenshot and include it as organized screenText. Defaults to false.
    screenText: NotRequired[bool]
    # Include a downscaled window screenshot with a full app observation. Defaults to true; since change checks and semantic-target child pages are always imageless.
    screenshot: NotRequired[bool]
    # Snapshot id from a prior look response. Returns a coarse change check instead of a tree.
    since: NotRequired[str]
    # App-scoped semantic name returned by a prior look; pages that element's children.
    target: NotRequired[LookParamsTarget]
    # Include the nested AX tree for app observations. Defaults to true for observation format and false for debug format.
    tree: NotRequired[bool]


class NavigateParams(TypedDict, total=False):
    """Navigate the active tab of a supported browser through its application scripting dictionary and verify the URL by read-back once the tab settles."""

    # Safari or Google Chrome, by name or exact bundle identifier.
    app: Required[str]
    # Absolute http or https URL, limited to 8192 bytes.
    url: Required[str]


class WindowsParams(TypedDict, total=False):
    """Enumerate browser windows authoritatively through the supported app's scripting dictionary and cross-check them against AX when available."""

    # Safari or Google Chrome, by name or exact bundle identifier.
    app: Required[str]


class TabsParams(TypedDict, total=False):
    """Enumerate browser tabs authoritatively through the supported app's scripting dictionary."""

    # Safari or Google Chrome, by name or exact bundle identifier.
    app: Required[str]
    # Optional one-based window index from windows().
    window: NotRequired[int]


class FindParams(TypedDict, total=False):
    """Resolve an AX locator against a fresh app snapshot."""

    # Bundle id, pid, exact app name, or partial app name.
    app: Required[str]
    # AX locator with role, subrole, label, title, value, description, identifier, actions, and ancestors.
    locator: Required[dict[str, Any]]


class WaitForValueParamsTarget(TypedDict, total=False):
    """Semantic element target object with required app and name fields. Run look first to observe canonical names."""

    # Bundle id, pid, app name, or partial app name.
    app: Required[str]
    # Semantic element name returned by look.
    name: Required[str]


class WaitForValueParams(TypedDict, total=False):
    """Poll readable accessibility state from an app-scoped semantic name until a contains, equals, or regex predicate holds, or a bounded timeout reports the last observed state."""

    # Succeed when any readable field contains this text.
    contains: NotRequired[str]
    # Succeed when any readable field exactly equals this text.
    equals: NotRequired[str]
    # Delay between polls. Defaults to 100 ms and is capped by the remaining timeout.
    intervalMs: NotRequired[int]
    # Succeed when any readable field matches this regular expression.
    matches: NotRequired[str]
    # App-scoped semantic name target returned by look.
    target: Required[WaitForValueParamsTarget]
    # Maximum time to poll before returning a failed timeout result. Defaults to 5000 ms and is capped at 60000 ms.
    timeoutMs: NotRequired[int]


class WaitForStabilityParams(TypedDict, total=False):
    """Poll full app observations until the accessibility surface remains unchanged for a stability window or changes from its initial state; timeout returns the final observation."""

    # Bundle id, pid, exact app name, or partial app name.
    app: Required[str]
    # stable waits for an unchanged stability window; changed waits for an observable app, tree, or focus change.
    condition: NotRequired[str]
    # Delay between observations. At least 10 ms and capped by the remaining timeout.
    intervalMs: NotRequired[int]
    # Required unchanged duration for the stable condition. Defaults to 300 ms and is capped at 10000 ms.
    stableMs: NotRequired[int]
    # Maximum wait. Defaults to 5000 ms and is capped at 60000 ms.
    timeoutMs: NotRequired[int]


class PermitParams(TypedDict, total=False):
    """Ask macOS to show the Accessibility permission prompt for the running Axon daemon identity."""


class RunParams(TypedDict, total=False):
    """Run a sequence of Axon actions from inline actions, a .axn path, or a path loaded first with inline actions appended."""

    # Ordered action objects, each with a tool field and that tool's normal arguments.
    actions: NotRequired[list[dict[str, Any]]]
    # Caller-supplied .axn argument values keyed by declared arg name. Valid only for args without a declared source.
    argValues: NotRequired[dict[str, Any]]
    # Continue after an action fails. Defaults to false.
    continueOnError: NotRequired[bool]
    # Trace the run without dispatching actions.
    dryRun: NotRequired[bool]
    # Write a revised copy of the .axn to this path when replay resolves through drifted locator evidence. The source file is never modified.
    healedPath: NotRequired[str]
    # Local .axn file path for the Axon daemon to read.
    path: NotRequired[str]


# Save recent recorded Axon calls as an editable .axn action file. Read calls are omitted unless includeReads is true.
SaveParams = TypedDict(
    "SaveParams",
    {
        # Optional starting call id, inclusive.
        "from": NotRequired[str],
        # Include read/context tools such as look and find. Defaults to false.
        "includeReads": NotRequired[bool],
        # Optional local path to write the .axn file.
        "path": NotRequired[str],
        # History session to export. Defaults to the daemon's default session.
        "sessionId": NotRequired[str],
        # Optional ending call id, inclusive.
        "to": NotRequired[str],
    },
    total=False,
)


class ClickParamsTarget1(TypedDict, total=False):
    """Semantic element target object with required app and name fields. Run look first to observe canonical names."""

    # Bundle id, pid, app name, or partial app name.
    app: Required[str]
    # Semantic element name returned by look.
    name: Required[str]


class ClickParamsTarget2Point(TypedDict, total=False):
    """Point target object: { point: { x, y, coordinateSpace, app } }, { app, coordinateSpace, point: { x, y } }, or { x, y, coordinateSpace }. screen and window coordinates are logical points in the platform accessibility coordinate system and are converted to native pointer coordinates for dispatch. screenshot coordinates are pixels in the returned encoded image after capture and any downscaling; Axon converts them by the encoded-image-to-window size ratios, never by assuming a fixed display scale. app and coordinateSpace may be stated on the point itself or beside it on the target object, and the most specific statement wins: the point, then the target object around it, then the top-level app parameter. window and screenshot points require an app from one of those places. Naming the app is what lets a point activate that application before it is clicked; it does not by itself qualify the coordinate for background delivery. Background delivery needs the window frame a coordinate was measured against, which only a derived point carries — from a window or screenshot conversion, or from a text location. A caller-supplied screen point therefore reaches its target through foreground delivery, activating the named app and proving it before dispatch, and refuses under backgroundOnly rather than posting into a process that may accept the events and do nothing. Raw points dispatch without element identity or occlusion verification; use a semantic name when fail-closed target validation is required."""

    # Application that owns this point. Required for a window or screenshot coordinate, and what binds a screen coordinate to a process instead of the shared input devices.
    app: NotRequired[str]
    # Coordinate space. Defaults to screen. screen and window use logical points in the platform accessibility coordinate system; screenshot uses returned encoded-image pixels.
    coordinateSpace: NotRequired[Literal["screen", "window", "screenshot"]]
    # Legacy alias for coordinateSpace.
    space: NotRequired[Literal["screen", "window", "screenshot"]]
    # Horizontal coordinate.
    x: Required[float]
    # Vertical coordinate.
    y: Required[float]


class ClickParamsTarget2(TypedDict, total=False):
    """Point target object: { point: { x, y, coordinateSpace, app } }, { app, coordinateSpace, point: { x, y } }, or { x, y, coordinateSpace }. screen and window coordinates are logical points in the platform accessibility coordinate system and are converted to native pointer coordinates for dispatch. screenshot coordinates are pixels in the returned encoded image after capture and any downscaling; Axon converts them by the encoded-image-to-window size ratios, never by assuming a fixed display scale. app and coordinateSpace may be stated on the point itself or beside it on the target object, and the most specific statement wins: the point, then the target object around it, then the top-level app parameter. window and screenshot points require an app from one of those places. Naming the app is what lets a point activate that application before it is clicked; it does not by itself qualify the coordinate for background delivery. Background delivery needs the window frame a coordinate was measured against, which only a derived point carries — from a window or screenshot conversion, or from a text location. A caller-supplied screen point therefore reaches its target through foreground delivery, activating the named app and proving it before dispatch, and refuses under backgroundOnly rather than posting into a process that may accept the events and do nothing. Raw points dispatch without element identity or occlusion verification; use a semantic name when fail-closed target validation is required."""

    # Application that owns this point. Required for a window or screenshot coordinate, and what binds a screen coordinate to a process instead of the shared input devices.
    app: NotRequired[str]
    # Coordinate space. Defaults to screen. screen and window use logical points in the platform accessibility coordinate system; screenshot uses returned encoded-image pixels.
    coordinateSpace: NotRequired[Literal["screen", "window", "screenshot"]]
    # Point target object: { point: { x, y, coordinateSpace, app } }, { app, coordinateSpace, point: { x, y } }, or { x, y, coordinateSpace }. screen and window coordinates are logical points in the platform accessibility coordinate system and are converted to native pointer coordinates for dispatch. screenshot coordinates are pixels in the returned encoded image after capture and any downscaling; Axon converts them by the encoded-image-to-window size ratios, never by assuming a fixed display scale. app and coordinateSpace may be stated on the point itself or beside it on the target object, and the most specific statement wins: the point, then the target object around it, then the top-level app parameter. window and screenshot points require an app from one of those places. Naming the app is what lets a point activate that application before it is clicked; it does not by itself qualify the coordinate for background delivery. Background delivery needs the window frame a coordinate was measured against, which only a derived point carries — from a window or screenshot conversion, or from a text location. A caller-supplied screen point therefore reaches its target through foreground delivery, activating the named app and proving it before dispatch, and refuses under backgroundOnly rather than posting into a process that may accept the events and do nothing. Raw points dispatch without element identity or occlusion verification; use a semantic name when fail-closed target validation is required.
    point: Required[ClickParamsTarget2Point]
    # Legacy alias for coordinateSpace.
    space: NotRequired[Literal["screen", "window", "screenshot"]]


class ClickParamsTarget3(TypedDict, total=False):
    """Point target object: { point: { x, y, coordinateSpace, app } }, { app, coordinateSpace, point: { x, y } }, or { x, y, coordinateSpace }. screen and window coordinates are logical points in the platform accessibility coordinate system and are converted to native pointer coordinates for dispatch. screenshot coordinates are pixels in the returned encoded image after capture and any downscaling; Axon converts them by the encoded-image-to-window size ratios, never by assuming a fixed display scale. app and coordinateSpace may be stated on the point itself or beside it on the target object, and the most specific statement wins: the point, then the target object around it, then the top-level app parameter. window and screenshot points require an app from one of those places. Naming the app is what lets a point activate that application before it is clicked; it does not by itself qualify the coordinate for background delivery. Background delivery needs the window frame a coordinate was measured against, which only a derived point carries — from a window or screenshot conversion, or from a text location. A caller-supplied screen point therefore reaches its target through foreground delivery, activating the named app and proving it before dispatch, and refuses under backgroundOnly rather than posting into a process that may accept the events and do nothing. Raw points dispatch without element identity or occlusion verification; use a semantic name when fail-closed target validation is required."""

    # Application that owns this point. Required for a window or screenshot coordinate, and what binds a screen coordinate to a process instead of the shared input devices.
    app: NotRequired[str]
    # Coordinate space. Defaults to screen. screen and window use logical points in the platform accessibility coordinate system; screenshot uses returned encoded-image pixels.
    coordinateSpace: NotRequired[Literal["screen", "window", "screenshot"]]
    # Legacy alias for coordinateSpace.
    space: NotRequired[Literal["screen", "window", "screenshot"]]
    # Horizontal coordinate.
    x: Required[float]
    # Vertical coordinate.
    y: Required[float]


class ClickParamsTarget4LocationText2Exact(TypedDict, total=False):
    # Whether matching preserves case.
    caseSensitive: NotRequired[bool]
    # Text fragment to match.
    contains: NotRequired[str]
    # Text to match exactly.
    exact: Required[str]


class ClickParamsTarget4LocationText2Contains(TypedDict, total=False):
    # Whether matching preserves case.
    caseSensitive: NotRequired[bool]
    # Text fragment to match.
    contains: Required[str]
    # Text to match exactly.
    exact: NotRequired[str]


class ClickParamsTarget4Location(TypedDict, total=False):
    # App containing the visible text.
    app: Required[str]
    # Text source. auto, the default, matches accessibility text first and falls back to screenshot OCR when accessibility matches nothing. ax and screenshot use only that source and never fall back.
    source: NotRequired[Literal["auto", "ax", "screenshot"]]
    # Text to match exactly, or an exact/contains matcher object.
    text: Required[str | ClickParamsTarget4LocationText2Exact | ClickParamsTarget4LocationText2Contains]


class ClickParamsTarget4(TypedDict, total=False):
    """Text location target object: { location: { app, text, source? } }. Resolves visible text to a click/drag/scroll point using AX text or screenshot OCR without callers providing coordinates. Rendered web content frequently exposes no accessibility text at all, so auto or screenshot is the reliable path for web links on macOS."""

    location: Required[ClickParamsTarget4Location]


class ClickParams(TypedDict, total=False):
    """Click an app-scoped semantic element name, explicit point, or text location."""

    # backgroundOnly (default) forbids activation, focus changes, real pointer movement, global keyboard input, and the clipboard, and returns a structured refusal instead. foregroundPermitted allows this one action to escalate; it is never inherited by later actions.
    deliveryPolicy: NotRequired[str]
    # Target to click.
    target: Required[ClickParamsTarget1 | ClickParamsTarget2 | ClickParamsTarget3 | ClickParamsTarget4]


class TypeParamsTarget(TypedDict, total=False):
    """Semantic element target object with required app and name fields. Run look first to observe canonical names."""

    # Bundle id, pid, app name, or partial app name.
    app: Required[str]
    # Semantic element name returned by look.
    name: Required[str]


class TypeParams(TypedDict, total=False):
    """Fill a writable field by setting AXValue directly on a target, avoiding focus and keystroke timing races."""

    # backgroundOnly (default) forbids activation, focus changes, real pointer movement, global keyboard input, and the clipboard, and returns a structured refusal instead. foregroundPermitted allows this one action to escalate; it is never inherited by later actions.
    deliveryPolicy: NotRequired[str]
    # App-scoped semantic name target for the writable field.
    target: Required[TypeParamsTarget]
    # New string value.
    value: Required[str]


class KeyboardParamsText(TypedDict, total=False):
    """Post keyboard input for shortcuts, special keys, or raw text when field-level type is not the right intent."""

    # Application that receives the input. Required for background delivery; without it only foregroundPermitted can reach the frontmost app.
    app: NotRequired[str]
    # backgroundOnly (default) forbids activation, focus changes, real pointer movement, global keyboard input, and the clipboard, and returns a structured refusal instead. foregroundPermitted allows this one action to escalate; it is never inherited by later actions.
    deliveryPolicy: NotRequired[str]
    # Recognized key or keystroke, for example End, Return, or cmd+shift+p. Unknown names are rejected.
    key: NotRequired[str]
    # Arbitrary text to enter exactly as provided.
    text: Required[str]


class KeyboardParamsKey(TypedDict, total=False):
    """Post keyboard input for shortcuts, special keys, or raw text when field-level type is not the right intent."""

    # Application that receives the input. Required for background delivery; without it only foregroundPermitted can reach the frontmost app.
    app: NotRequired[str]
    # backgroundOnly (default) forbids activation, focus changes, real pointer movement, global keyboard input, and the clipboard, and returns a structured refusal instead. foregroundPermitted allows this one action to escalate; it is never inherited by later actions.
    deliveryPolicy: NotRequired[str]
    # Recognized key or keystroke, for example End, Return, or cmd+shift+p. Unknown names are rejected.
    key: Required[str]
    # Arbitrary text to enter exactly as provided.
    text: NotRequired[str]


# Post keyboard input for shortcuts, special keys, or raw text when field-level type is not the right intent.
KeyboardParams: TypeAlias = KeyboardParamsText | KeyboardParamsKey


class ScrollParamsTarget1(TypedDict, total=False):
    """Semantic element target object with required app and name fields. Run look first to observe canonical names."""

    # Bundle id, pid, app name, or partial app name.
    app: Required[str]
    # Semantic element name returned by look.
    name: Required[str]


class ScrollParamsTarget2Point(TypedDict, total=False):
    """Point target object: { point: { x, y, coordinateSpace, app } }, { app, coordinateSpace, point: { x, y } }, or { x, y, coordinateSpace }. screen and window coordinates are logical points in the platform accessibility coordinate system and are converted to native pointer coordinates for dispatch. screenshot coordinates are pixels in the returned encoded image after capture and any downscaling; Axon converts them by the encoded-image-to-window size ratios, never by assuming a fixed display scale. app and coordinateSpace may be stated on the point itself or beside it on the target object, and the most specific statement wins: the point, then the target object around it, then the top-level app parameter. window and screenshot points require an app from one of those places. Naming the app is what lets a point activate that application before it is clicked; it does not by itself qualify the coordinate for background delivery. Background delivery needs the window frame a coordinate was measured against, which only a derived point carries — from a window or screenshot conversion, or from a text location. A caller-supplied screen point therefore reaches its target through foreground delivery, activating the named app and proving it before dispatch, and refuses under backgroundOnly rather than posting into a process that may accept the events and do nothing. Raw points dispatch without element identity or occlusion verification; use a semantic name when fail-closed target validation is required."""

    # Application that owns this point. Required for a window or screenshot coordinate, and what binds a screen coordinate to a process instead of the shared input devices.
    app: NotRequired[str]
    # Coordinate space. Defaults to screen. screen and window use logical points in the platform accessibility coordinate system; screenshot uses returned encoded-image pixels.
    coordinateSpace: NotRequired[Literal["screen", "window", "screenshot"]]
    # Legacy alias for coordinateSpace.
    space: NotRequired[Literal["screen", "window", "screenshot"]]
    # Horizontal coordinate.
    x: Required[float]
    # Vertical coordinate.
    y: Required[float]


class ScrollParamsTarget2(TypedDict, total=False):
    """Point target object: { point: { x, y, coordinateSpace, app } }, { app, coordinateSpace, point: { x, y } }, or { x, y, coordinateSpace }. screen and window coordinates are logical points in the platform accessibility coordinate system and are converted to native pointer coordinates for dispatch. screenshot coordinates are pixels in the returned encoded image after capture and any downscaling; Axon converts them by the encoded-image-to-window size ratios, never by assuming a fixed display scale. app and coordinateSpace may be stated on the point itself or beside it on the target object, and the most specific statement wins: the point, then the target object around it, then the top-level app parameter. window and screenshot points require an app from one of those places. Naming the app is what lets a point activate that application before it is clicked; it does not by itself qualify the coordinate for background delivery. Background delivery needs the window frame a coordinate was measured against, which only a derived point carries — from a window or screenshot conversion, or from a text location. A caller-supplied screen point therefore reaches its target through foreground delivery, activating the named app and proving it before dispatch, and refuses under backgroundOnly rather than posting into a process that may accept the events and do nothing. Raw points dispatch without element identity or occlusion verification; use a semantic name when fail-closed target validation is required."""

    # Application that owns this point. Required for a window or screenshot coordinate, and what binds a screen coordinate to a process instead of the shared input devices.
    app: NotRequired[str]
    # Coordinate space. Defaults to screen. screen and window use logical points in the platform accessibility coordinate system; screenshot uses returned encoded-image pixels.
    coordinateSpace: NotRequired[Literal["screen", "window", "screenshot"]]
    # Point target object: { point: { x, y, coordinateSpace, app } }, { app, coordinateSpace, point: { x, y } }, or { x, y, coordinateSpace }. screen and window coordinates are logical points in the platform accessibility coordinate system and are converted to native pointer coordinates for dispatch. screenshot coordinates are pixels in the returned encoded image after capture and any downscaling; Axon converts them by the encoded-image-to-window size ratios, never by assuming a fixed display scale. app and coordinateSpace may be stated on the point itself or beside it on the target object, and the most specific statement wins: the point, then the target object around it, then the top-level app parameter. window and screenshot points require an app from one of those places. Naming the app is what lets a point activate that application before it is clicked; it does not by itself qualify the coordinate for background delivery. Background delivery needs the window frame a coordinate was measured against, which only a derived point carries — from a window or screenshot conversion, or from a text location. A caller-supplied screen point therefore reaches its target through foreground delivery, activating the named app and proving it before dispatch, and refuses under backgroundOnly rather than posting into a process that may accept the events and do nothing. Raw points dispatch without element identity or occlusion verification; use a semantic name when fail-closed target validation is required.
    point: Required[ScrollParamsTarget2Point]
    # Legacy alias for coordinateSpace.
    space: NotRequired[Literal["screen", "window", "screenshot"]]


class ScrollParamsTarget3(TypedDict, total=False):
    """Point target object: { point: { x, y, coordinateSpace, app } }, { app, coordinateSpace, point: { x, y } }, or { x, y, coordinateSpace }. screen and window coordinates are logical points in the platform accessibility coordinate system and are converted to native pointer coordinates for dispatch. screenshot coordinates are pixels in the returned encoded image after capture and any downscaling; Axon converts them by the encoded-image-to-window size ratios, never by assuming a fixed display scale. app and coordinateSpace may be stated on the point itself or beside it on the target object, and the most specific statement wins: the point, then the target object around it, then the top-level app parameter. window and screenshot points require an app from one of those places. Naming the app is what lets a point activate that application before it is clicked; it does not by itself qualify the coordinate for background delivery. Background delivery needs the window frame a coordinate was measured against, which only a derived point carries — from a window or screenshot conversion, or from a text location. A caller-supplied screen point therefore reaches its target through foreground delivery, activating the named app and proving it before dispatch, and refuses under backgroundOnly rather than posting into a process that may accept the events and do nothing. Raw points dispatch without element identity or occlusion verification; use a semantic name when fail-closed target validation is required."""

    # Application that owns this point. Required for a window or screenshot coordinate, and what binds a screen coordinate to a process instead of the shared input devices.
    app: NotRequired[str]
    # Coordinate space. Defaults to screen. screen and window use logical points in the platform accessibility coordinate system; screenshot uses returned encoded-image pixels.
    coordinateSpace: NotRequired[Literal["screen", "window", "screenshot"]]
    # Legacy alias for coordinateSpace.
    space: NotRequired[Literal["screen", "window", "screenshot"]]
    # Horizontal coordinate.
    x: Required[float]
    # Vertical coordinate.
    y: Required[float]


class ScrollParamsTarget4LocationText2Exact(TypedDict, total=False):
    # Whether matching preserves case.
    caseSensitive: NotRequired[bool]
    # Text fragment to match.
    contains: NotRequired[str]
    # Text to match exactly.
    exact: Required[str]


class ScrollParamsTarget4LocationText2Contains(TypedDict, total=False):
    # Whether matching preserves case.
    caseSensitive: NotRequired[bool]
    # Text fragment to match.
    contains: Required[str]
    # Text to match exactly.
    exact: NotRequired[str]


class ScrollParamsTarget4Location(TypedDict, total=False):
    # App containing the visible text.
    app: Required[str]
    # Text source. auto, the default, matches accessibility text first and falls back to screenshot OCR when accessibility matches nothing. ax and screenshot use only that source and never fall back.
    source: NotRequired[Literal["auto", "ax", "screenshot"]]
    # Text to match exactly, or an exact/contains matcher object.
    text: Required[str | ScrollParamsTarget4LocationText2Exact | ScrollParamsTarget4LocationText2Contains]


class ScrollParamsTarget4(TypedDict, total=False):
    """Text location target object: { location: { app, text, source? } }. Resolves visible text to a click/drag/scroll point using AX text or screenshot OCR without callers providing coordinates. Rendered web content frequently exposes no accessibility text at all, so auto or screenshot is the reliable path for web links on macOS."""

    location: Required[ScrollParamsTarget4Location]


class ScrollParams(TypedDict, total=False):
    """Scroll an accessibility surface by resolving an offscreen descendant and requesting AXScrollToVisible."""

    # Optional app used to resolve a scroll surface without activating it.
    app: NotRequired[str]
    # backgroundOnly (default) forbids activation, focus changes, real pointer movement, global keyboard input, and the clipboard, and returns a structured refusal instead. foregroundPermitted allows this one action to escalate; it is never inherited by later actions.
    deliveryPolicy: NotRequired[str]
    # Horizontal scroll delta in pixels. Defaults to 0.
    deltaX: NotRequired[float]
    # Vertical scroll delta in pixels. Defaults to -120.
    deltaY: NotRequired[float]
    # Optional target to scroll or resolve into view.
    target: NotRequired[ScrollParamsTarget1 | ScrollParamsTarget2 | ScrollParamsTarget3 | ScrollParamsTarget4]


class DragParamsFrom1(TypedDict, total=False):
    """Semantic element target object with required app and name fields. Run look first to observe canonical names."""

    # Bundle id, pid, app name, or partial app name.
    app: Required[str]
    # Semantic element name returned by look.
    name: Required[str]


class DragParamsFrom2Point(TypedDict, total=False):
    """Point target object: { point: { x, y, coordinateSpace, app } }, { app, coordinateSpace, point: { x, y } }, or { x, y, coordinateSpace }. screen and window coordinates are logical points in the platform accessibility coordinate system and are converted to native pointer coordinates for dispatch. screenshot coordinates are pixels in the returned encoded image after capture and any downscaling; Axon converts them by the encoded-image-to-window size ratios, never by assuming a fixed display scale. app and coordinateSpace may be stated on the point itself or beside it on the target object, and the most specific statement wins: the point, then the target object around it, then the top-level app parameter. window and screenshot points require an app from one of those places. Naming the app is what lets a point activate that application before it is clicked; it does not by itself qualify the coordinate for background delivery. Background delivery needs the window frame a coordinate was measured against, which only a derived point carries — from a window or screenshot conversion, or from a text location. A caller-supplied screen point therefore reaches its target through foreground delivery, activating the named app and proving it before dispatch, and refuses under backgroundOnly rather than posting into a process that may accept the events and do nothing. Raw points dispatch without element identity or occlusion verification; use a semantic name when fail-closed target validation is required."""

    # Application that owns this point. Required for a window or screenshot coordinate, and what binds a screen coordinate to a process instead of the shared input devices.
    app: NotRequired[str]
    # Coordinate space. Defaults to screen. screen and window use logical points in the platform accessibility coordinate system; screenshot uses returned encoded-image pixels.
    coordinateSpace: NotRequired[Literal["screen", "window", "screenshot"]]
    # Legacy alias for coordinateSpace.
    space: NotRequired[Literal["screen", "window", "screenshot"]]
    # Horizontal coordinate.
    x: Required[float]
    # Vertical coordinate.
    y: Required[float]


class DragParamsFrom2(TypedDict, total=False):
    """Point target object: { point: { x, y, coordinateSpace, app } }, { app, coordinateSpace, point: { x, y } }, or { x, y, coordinateSpace }. screen and window coordinates are logical points in the platform accessibility coordinate system and are converted to native pointer coordinates for dispatch. screenshot coordinates are pixels in the returned encoded image after capture and any downscaling; Axon converts them by the encoded-image-to-window size ratios, never by assuming a fixed display scale. app and coordinateSpace may be stated on the point itself or beside it on the target object, and the most specific statement wins: the point, then the target object around it, then the top-level app parameter. window and screenshot points require an app from one of those places. Naming the app is what lets a point activate that application before it is clicked; it does not by itself qualify the coordinate for background delivery. Background delivery needs the window frame a coordinate was measured against, which only a derived point carries — from a window or screenshot conversion, or from a text location. A caller-supplied screen point therefore reaches its target through foreground delivery, activating the named app and proving it before dispatch, and refuses under backgroundOnly rather than posting into a process that may accept the events and do nothing. Raw points dispatch without element identity or occlusion verification; use a semantic name when fail-closed target validation is required."""

    # Application that owns this point. Required for a window or screenshot coordinate, and what binds a screen coordinate to a process instead of the shared input devices.
    app: NotRequired[str]
    # Coordinate space. Defaults to screen. screen and window use logical points in the platform accessibility coordinate system; screenshot uses returned encoded-image pixels.
    coordinateSpace: NotRequired[Literal["screen", "window", "screenshot"]]
    # Point target object: { point: { x, y, coordinateSpace, app } }, { app, coordinateSpace, point: { x, y } }, or { x, y, coordinateSpace }. screen and window coordinates are logical points in the platform accessibility coordinate system and are converted to native pointer coordinates for dispatch. screenshot coordinates are pixels in the returned encoded image after capture and any downscaling; Axon converts them by the encoded-image-to-window size ratios, never by assuming a fixed display scale. app and coordinateSpace may be stated on the point itself or beside it on the target object, and the most specific statement wins: the point, then the target object around it, then the top-level app parameter. window and screenshot points require an app from one of those places. Naming the app is what lets a point activate that application before it is clicked; it does not by itself qualify the coordinate for background delivery. Background delivery needs the window frame a coordinate was measured against, which only a derived point carries — from a window or screenshot conversion, or from a text location. A caller-supplied screen point therefore reaches its target through foreground delivery, activating the named app and proving it before dispatch, and refuses under backgroundOnly rather than posting into a process that may accept the events and do nothing. Raw points dispatch without element identity or occlusion verification; use a semantic name when fail-closed target validation is required.
    point: Required[DragParamsFrom2Point]
    # Legacy alias for coordinateSpace.
    space: NotRequired[Literal["screen", "window", "screenshot"]]


class DragParamsFrom3(TypedDict, total=False):
    """Point target object: { point: { x, y, coordinateSpace, app } }, { app, coordinateSpace, point: { x, y } }, or { x, y, coordinateSpace }. screen and window coordinates are logical points in the platform accessibility coordinate system and are converted to native pointer coordinates for dispatch. screenshot coordinates are pixels in the returned encoded image after capture and any downscaling; Axon converts them by the encoded-image-to-window size ratios, never by assuming a fixed display scale. app and coordinateSpace may be stated on the point itself or beside it on the target object, and the most specific statement wins: the point, then the target object around it, then the top-level app parameter. window and screenshot points require an app from one of those places. Naming the app is what lets a point activate that application before it is clicked; it does not by itself qualify the coordinate for background delivery. Background delivery needs the window frame a coordinate was measured against, which only a derived point carries — from a window or screenshot conversion, or from a text location. A caller-supplied screen point therefore reaches its target through foreground delivery, activating the named app and proving it before dispatch, and refuses under backgroundOnly rather than posting into a process that may accept the events and do nothing. Raw points dispatch without element identity or occlusion verification; use a semantic name when fail-closed target validation is required."""

    # Application that owns this point. Required for a window or screenshot coordinate, and what binds a screen coordinate to a process instead of the shared input devices.
    app: NotRequired[str]
    # Coordinate space. Defaults to screen. screen and window use logical points in the platform accessibility coordinate system; screenshot uses returned encoded-image pixels.
    coordinateSpace: NotRequired[Literal["screen", "window", "screenshot"]]
    # Legacy alias for coordinateSpace.
    space: NotRequired[Literal["screen", "window", "screenshot"]]
    # Horizontal coordinate.
    x: Required[float]
    # Vertical coordinate.
    y: Required[float]


class DragParamsFrom4LocationText2Exact(TypedDict, total=False):
    # Whether matching preserves case.
    caseSensitive: NotRequired[bool]
    # Text fragment to match.
    contains: NotRequired[str]
    # Text to match exactly.
    exact: Required[str]


class DragParamsFrom4LocationText2Contains(TypedDict, total=False):
    # Whether matching preserves case.
    caseSensitive: NotRequired[bool]
    # Text fragment to match.
    contains: Required[str]
    # Text to match exactly.
    exact: NotRequired[str]


class DragParamsFrom4Location(TypedDict, total=False):
    # App containing the visible text.
    app: Required[str]
    # Text source. auto, the default, matches accessibility text first and falls back to screenshot OCR when accessibility matches nothing. ax and screenshot use only that source and never fall back.
    source: NotRequired[Literal["auto", "ax", "screenshot"]]
    # Text to match exactly, or an exact/contains matcher object.
    text: Required[str | DragParamsFrom4LocationText2Exact | DragParamsFrom4LocationText2Contains]


class DragParamsFrom4(TypedDict, total=False):
    """Text location target object: { location: { app, text, source? } }. Resolves visible text to a click/drag/scroll point using AX text or screenshot OCR without callers providing coordinates. Rendered web content frequently exposes no accessibility text at all, so auto or screenshot is the reliable path for web links on macOS."""

    location: Required[DragParamsFrom4Location]


class DragParamsTo1(TypedDict, total=False):
    """Semantic element target object with required app and name fields. Run look first to observe canonical names."""

    # Bundle id, pid, app name, or partial app name.
    app: Required[str]
    # Semantic element name returned by look.
    name: Required[str]


class DragParamsTo2Point(TypedDict, total=False):
    """Point target object: { point: { x, y, coordinateSpace, app } }, { app, coordinateSpace, point: { x, y } }, or { x, y, coordinateSpace }. screen and window coordinates are logical points in the platform accessibility coordinate system and are converted to native pointer coordinates for dispatch. screenshot coordinates are pixels in the returned encoded image after capture and any downscaling; Axon converts them by the encoded-image-to-window size ratios, never by assuming a fixed display scale. app and coordinateSpace may be stated on the point itself or beside it on the target object, and the most specific statement wins: the point, then the target object around it, then the top-level app parameter. window and screenshot points require an app from one of those places. Naming the app is what lets a point activate that application before it is clicked; it does not by itself qualify the coordinate for background delivery. Background delivery needs the window frame a coordinate was measured against, which only a derived point carries — from a window or screenshot conversion, or from a text location. A caller-supplied screen point therefore reaches its target through foreground delivery, activating the named app and proving it before dispatch, and refuses under backgroundOnly rather than posting into a process that may accept the events and do nothing. Raw points dispatch without element identity or occlusion verification; use a semantic name when fail-closed target validation is required."""

    # Application that owns this point. Required for a window or screenshot coordinate, and what binds a screen coordinate to a process instead of the shared input devices.
    app: NotRequired[str]
    # Coordinate space. Defaults to screen. screen and window use logical points in the platform accessibility coordinate system; screenshot uses returned encoded-image pixels.
    coordinateSpace: NotRequired[Literal["screen", "window", "screenshot"]]
    # Legacy alias for coordinateSpace.
    space: NotRequired[Literal["screen", "window", "screenshot"]]
    # Horizontal coordinate.
    x: Required[float]
    # Vertical coordinate.
    y: Required[float]


class DragParamsTo2(TypedDict, total=False):
    """Point target object: { point: { x, y, coordinateSpace, app } }, { app, coordinateSpace, point: { x, y } }, or { x, y, coordinateSpace }. screen and window coordinates are logical points in the platform accessibility coordinate system and are converted to native pointer coordinates for dispatch. screenshot coordinates are pixels in the returned encoded image after capture and any downscaling; Axon converts them by the encoded-image-to-window size ratios, never by assuming a fixed display scale. app and coordinateSpace may be stated on the point itself or beside it on the target object, and the most specific statement wins: the point, then the target object around it, then the top-level app parameter. window and screenshot points require an app from one of those places. Naming the app is what lets a point activate that application before it is clicked; it does not by itself qualify the coordinate for background delivery. Background delivery needs the window frame a coordinate was measured against, which only a derived point carries — from a window or screenshot conversion, or from a text location. A caller-supplied screen point therefore reaches its target through foreground delivery, activating the named app and proving it before dispatch, and refuses under backgroundOnly rather than posting into a process that may accept the events and do nothing. Raw points dispatch without element identity or occlusion verification; use a semantic name when fail-closed target validation is required."""

    # Application that owns this point. Required for a window or screenshot coordinate, and what binds a screen coordinate to a process instead of the shared input devices.
    app: NotRequired[str]
    # Coordinate space. Defaults to screen. screen and window use logical points in the platform accessibility coordinate system; screenshot uses returned encoded-image pixels.
    coordinateSpace: NotRequired[Literal["screen", "window", "screenshot"]]
    # Point target object: { point: { x, y, coordinateSpace, app } }, { app, coordinateSpace, point: { x, y } }, or { x, y, coordinateSpace }. screen and window coordinates are logical points in the platform accessibility coordinate system and are converted to native pointer coordinates for dispatch. screenshot coordinates are pixels in the returned encoded image after capture and any downscaling; Axon converts them by the encoded-image-to-window size ratios, never by assuming a fixed display scale. app and coordinateSpace may be stated on the point itself or beside it on the target object, and the most specific statement wins: the point, then the target object around it, then the top-level app parameter. window and screenshot points require an app from one of those places. Naming the app is what lets a point activate that application before it is clicked; it does not by itself qualify the coordinate for background delivery. Background delivery needs the window frame a coordinate was measured against, which only a derived point carries — from a window or screenshot conversion, or from a text location. A caller-supplied screen point therefore reaches its target through foreground delivery, activating the named app and proving it before dispatch, and refuses under backgroundOnly rather than posting into a process that may accept the events and do nothing. Raw points dispatch without element identity or occlusion verification; use a semantic name when fail-closed target validation is required.
    point: Required[DragParamsTo2Point]
    # Legacy alias for coordinateSpace.
    space: NotRequired[Literal["screen", "window", "screenshot"]]


class DragParamsTo3(TypedDict, total=False):
    """Point target object: { point: { x, y, coordinateSpace, app } }, { app, coordinateSpace, point: { x, y } }, or { x, y, coordinateSpace }. screen and window coordinates are logical points in the platform accessibility coordinate system and are converted to native pointer coordinates for dispatch. screenshot coordinates are pixels in the returned encoded image after capture and any downscaling; Axon converts them by the encoded-image-to-window size ratios, never by assuming a fixed display scale. app and coordinateSpace may be stated on the point itself or beside it on the target object, and the most specific statement wins: the point, then the target object around it, then the top-level app parameter. window and screenshot points require an app from one of those places. Naming the app is what lets a point activate that application before it is clicked; it does not by itself qualify the coordinate for background delivery. Background delivery needs the window frame a coordinate was measured against, which only a derived point carries — from a window or screenshot conversion, or from a text location. A caller-supplied screen point therefore reaches its target through foreground delivery, activating the named app and proving it before dispatch, and refuses under backgroundOnly rather than posting into a process that may accept the events and do nothing. Raw points dispatch without element identity or occlusion verification; use a semantic name when fail-closed target validation is required."""

    # Application that owns this point. Required for a window or screenshot coordinate, and what binds a screen coordinate to a process instead of the shared input devices.
    app: NotRequired[str]
    # Coordinate space. Defaults to screen. screen and window use logical points in the platform accessibility coordinate system; screenshot uses returned encoded-image pixels.
    coordinateSpace: NotRequired[Literal["screen", "window", "screenshot"]]
    # Legacy alias for coordinateSpace.
    space: NotRequired[Literal["screen", "window", "screenshot"]]
    # Horizontal coordinate.
    x: Required[float]
    # Vertical coordinate.
    y: Required[float]


class DragParamsTo4LocationText2Exact(TypedDict, total=False):
    # Whether matching preserves case.
    caseSensitive: NotRequired[bool]
    # Text fragment to match.
    contains: NotRequired[str]
    # Text to match exactly.
    exact: Required[str]


class DragParamsTo4LocationText2Contains(TypedDict, total=False):
    # Whether matching preserves case.
    caseSensitive: NotRequired[bool]
    # Text fragment to match.
    contains: Required[str]
    # Text to match exactly.
    exact: NotRequired[str]


class DragParamsTo4Location(TypedDict, total=False):
    # App containing the visible text.
    app: Required[str]
    # Text source. auto, the default, matches accessibility text first and falls back to screenshot OCR when accessibility matches nothing. ax and screenshot use only that source and never fall back.
    source: NotRequired[Literal["auto", "ax", "screenshot"]]
    # Text to match exactly, or an exact/contains matcher object.
    text: Required[str | DragParamsTo4LocationText2Exact | DragParamsTo4LocationText2Contains]


class DragParamsTo4(TypedDict, total=False):
    """Text location target object: { location: { app, text, source? } }. Resolves visible text to a click/drag/scroll point using AX text or screenshot OCR without callers providing coordinates. Rendered web content frequently exposes no accessibility text at all, so auto or screenshot is the reliable path for web links on macOS."""

    location: Required[DragParamsTo4Location]


# Drag from one semantic name, explicit point, or text location to another. Pointer dispatch and verified semantic outcome are reported separately.
DragParams = TypedDict(
    "DragParams",
    {
        # Application that owns the drag. Required for background delivery; also the app foregroundPermitted activates and restores.
        "app": NotRequired[str],
        # backgroundOnly (default) forbids activation, focus changes, real pointer movement, global keyboard input, and the clipboard, and returns a structured refusal instead. foregroundPermitted allows this one action to escalate; it is never inherited by later actions.
        "deliveryPolicy": NotRequired[str],
        # Optional drag duration in milliseconds. The pointer path still emits threshold and intermediate drag events.
        "durationMs": NotRequired[int],
        # Optional post-action facts used by run to verify semantic success. Direct drag calls without a verified postcondition report an unverified semantic outcome.
        "expects": NotRequired[list[dict[str, Any]]],
        # Starting semantic name, point, or text location.
        "from": Required[DragParamsFrom1 | DragParamsFrom2 | DragParamsFrom3 | DragParamsFrom4],
        # Ending semantic name, point, or text location.
        "to": Required[DragParamsTo1 | DragParamsTo2 | DragParamsTo3 | DragParamsTo4],
    },
    total=False,
)


class InvokeParamsTarget(TypedDict, total=False):
    """Semantic element target object with required app and name fields. Run look first to observe canonical names."""

    # Bundle id, pid, app name, or partial app name.
    app: Required[str]
    # Semantic element name returned by look.
    name: Required[str]


class InvokeParams(TypedDict, total=False):
    """Invoke a named accessibility action on an app-scoped semantic element name."""

    # backgroundOnly (default) forbids activation, focus changes, real pointer movement, global keyboard input, and the clipboard, and returns a structured refusal instead. foregroundPermitted allows this one action to escalate; it is never inherited by later actions.
    deliveryPolicy: NotRequired[str]
    # Accessibility action name, for example AXPress or AXShowMenu.
    name: Required[str]
    # App-scoped semantic name target.
    target: Required[InvokeParamsTarget]


class RawClient(Protocol):
    """One method per tool in the committed tool surface, typed by that tool's schema."""

    def capture_screen(self, params: CaptureScreenParams | None = None) -> dict[str, Any]:
        """Capture the user-authorized desktop ScreenCast source. The selected source is not associated with any application."""
        ...

    def look(self, params: LookParams | None = None) -> dict[str, Any]:
        """Observe Axon's current surface: no app lists apps, app captures state, a semantic target pages children, and since returns a change check. An observation whose note is no-windows means the application is running with no window open; the tree still holds its menu bar, so open one through the application's own File > New Window item before acting."""
        ...

    def navigate(self, params: NavigateParams) -> dict[str, Any]:
        """Navigate the active tab of a supported browser through its application scripting dictionary and verify the URL by read-back once the tab settles."""
        ...

    def windows(self, params: WindowsParams) -> dict[str, Any]:
        """Enumerate browser windows authoritatively through the supported app's scripting dictionary and cross-check them against AX when available."""
        ...

    def tabs(self, params: TabsParams) -> dict[str, Any]:
        """Enumerate browser tabs authoritatively through the supported app's scripting dictionary."""
        ...

    def find(self, params: FindParams) -> dict[str, Any]:
        """Resolve an AX locator against a fresh app snapshot."""
        ...

    def wait_for_value(self, params: WaitForValueParams) -> dict[str, Any]:
        """Poll readable accessibility state from an app-scoped semantic name until a contains, equals, or regex predicate holds, or a bounded timeout reports the last observed state."""
        ...

    def wait_for_stability(self, params: WaitForStabilityParams) -> dict[str, Any]:
        """Poll full app observations until the accessibility surface remains unchanged for a stability window or changes from its initial state; timeout returns the final observation."""
        ...

    def permit(self, params: PermitParams | None = None) -> dict[str, Any]:
        """Ask macOS to show the Accessibility permission prompt for the running Axon daemon identity."""
        ...

    def run(self, params: RunParams | None = None) -> dict[str, Any]:
        """Run a sequence of Axon actions from inline actions, a .axn path, or a path loaded first with inline actions appended."""
        ...

    def save(self, params: SaveParams | None = None) -> dict[str, Any]:
        """Save recent recorded Axon calls as an editable .axn action file. Read calls are omitted unless includeReads is true."""
        ...

    def click(self, params: ClickParams) -> dict[str, Any]:
        """Click an app-scoped semantic element name, explicit point, or text location."""
        ...

    def type(self, params: TypeParams) -> dict[str, Any]:
        """Fill a writable field by setting AXValue directly on a target, avoiding focus and keystroke timing races."""
        ...

    def keyboard(self, params: KeyboardParams) -> dict[str, Any]:
        """Post keyboard input for shortcuts, special keys, or raw text when field-level type is not the right intent."""
        ...

    def scroll(self, params: ScrollParams | None = None) -> dict[str, Any]:
        """Scroll an accessibility surface by resolving an offscreen descendant and requesting AXScrollToVisible."""
        ...

    def drag(self, params: DragParams) -> dict[str, Any]:
        """Drag from one semantic name, explicit point, or text location to another. Pointer dispatch and verified semantic outcome are reported separately."""
        ...

    def invoke(self, params: InvokeParams) -> dict[str, Any]:
        """Invoke a named accessibility action on an app-scoped semantic element name."""
        ...
