import { branchesOf, demandsParams, type JsonSchema, type ToolSurface } from "./schema.ts";

const identifier = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const propertyName = (name: string) => identifier.test(name) ? name : JSON.stringify(name);
const literal = (value: unknown) => value === null ? "null" : JSON.stringify(value);
const pascal = (name: string) => name.split(/[^A-Za-z0-9]+/).filter(Boolean)
  .map((part) => part[0]!.toUpperCase() + part.slice(1)).join("");
const jsdoc = (text: string, indent = "") => `${indent}/**\n${text.split("\n").map((line) => `${indent} * ${line.replaceAll("*/", "*\\/")}`).join("\n")}\n${indent} */`;

function objectType(schema: JsonSchema, alsoRequired: readonly string[] = []): string {
  const required = new Set([...(schema.required ?? []), ...alsoRequired]);
  const properties = Object.entries(schema.properties ?? {}).map(([name, value]) => {
    const doc = value.description ? `${jsdoc(value.description, "  ")}\n` : "";
    return `${doc}  ${propertyName(name)}${required.has(name) ? "" : "?"}: ${schemaType(value)};`;
  });
  if (schema.additionalProperties && schema.additionalProperties !== true) {
    properties.push(`  [key: string]: ${schemaType(schema.additionalProperties)};`);
  } else if (schema.additionalProperties === true) {
    properties.push("  [key: string]: unknown;");
  }
  return properties.length ? `{\n${properties.join("\n")}\n}` : "Record<string, never>";
}

function schemaType(schema: JsonSchema): string {
  if (schema.const !== undefined) return literal(schema.const);
  if (schema.enum) return schema.enum.map(literal).join(" | ");
  const { refinements, variants } = branchesOf(schema);
  if (variants.length) return variants.map(schemaType).join(" | ");
  if (Array.isArray(schema.type)) return schema.type.map((type) => schemaType({ type })).join(" | ");
  const type = schema.type ?? (schema.properties ? "object" : undefined);
  switch (type) {
    case "string": return "string";
    case "number": case "integer": return "number";
    case "boolean": return "boolean";
    case "null": return "null";
    case "array": return `Array<${schemaType(schema.items ?? {})}>`;
    case "object":
      return refinements.length
        ? refinements.map((branch) => objectType(schema, branch.required ?? [])).join(" | ")
        : objectType(schema);
    default: return "unknown";
  }
}

/** A single object literal becomes an interface; anything else stays a type alias. */
function declaration(name: string, schema: JsonSchema): string {
  const body = schemaType(schema);
  const single = branchesOf(schema).refinements.length === 0 && body.startsWith("{");
  return single ? `export interface ${name} ${body}` : `export type ${name} = ${body};`;
}

export function renderTypeScript(surface: ToolSurface): string {
  const interfaces = surface.tools.map((tool) => {
    const name = `${pascal(tool.name)}Params`;
    return `${jsdoc(tool.description)}\n${declaration(name, tool.inputSchema)}`;
  }).join("\n\n");
  const methods = surface.tools.map((tool) => {
    const optional = demandsParams(tool.inputSchema) ? "" : "?";
    return `${jsdoc(tool.description, "  ")}\n  ${propertyName(tool.socketMethod)}(params${optional}: ${pascal(tool.name)}Params): Promise<Record<string, unknown>>;`;
  }).join("\n");
  const availability = Object.fromEntries(surface.tools.map((tool) => [tool.socketMethod, tool.availability]));
  return `// Generated by sdk/generate.ts from schema/tool-surface-v1.json. Do not edit.\n\n` +
    `export const schemaProductVersion = ${JSON.stringify(surface.productVersion)} as const;\n\n` +
    `/** Per-tool platform availability, keyed by socket method then by daemon facade. */\n` +
    `export const availability = ${JSON.stringify(availability, null, 2)} as const;\n\n` +
    `${interfaces}\n\nexport interface RawClient {\n${methods}\n}\n`;
}
