import type { JsonSchema, ToolSurface } from "./schema.ts";

const identifier = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const propertyName = (name: string) => identifier.test(name) ? name : JSON.stringify(name);
const literal = (value: unknown) => value === null ? "null" : JSON.stringify(value);
const pascal = (name: string) => name.split(/[^A-Za-z0-9]+/).filter(Boolean)
  .map((part) => part[0]!.toUpperCase() + part.slice(1)).join("");
const jsdoc = (text: string, indent = "") => `${indent}/**\n${text.split("\n").map((line) => `${indent} * ${line.replaceAll("*/", "*\\/")}`).join("\n")}\n${indent} */`;

function schemaType(schema: JsonSchema): string {
  if (schema.const !== undefined) return literal(schema.const);
  if (schema.enum) return schema.enum.map(literal).join(" | ");
  if (schema.anyOf) return schema.anyOf.map(schemaType).join(" | ");
  if (schema.oneOf) return schema.oneOf.map(schemaType).join(" | ");
  if (Array.isArray(schema.type)) return schema.type.map((type) => schemaType({ type })).join(" | ");
  const type = schema.type ?? (schema.properties ? "object" : undefined);
  switch (type) {
    case "string": return "string";
    case "number": case "integer": return "number";
    case "boolean": return "boolean";
    case "null": return "null";
    case "array": return `Array<${schemaType(schema.items ?? {})}>`;
    case "object": {
      const required = new Set(schema.required ?? []);
      const properties = Object.entries(schema.properties ?? {}).map(([name, value]) => {
        const doc = value.description ? `${jsdoc(value.description, "  ")}\n` : "";
        return `${doc}  ${propertyName(name)}${required.has(name) ? "" : "?"}: ${schemaType(value)};`;
      });
      if (schema.additionalProperties && schema.additionalProperties !== true) {
        properties.push(`  [key: string]: ${schemaType(schema.additionalProperties)};`);
      } else if (schema.additionalProperties === true) {
        properties.push("  [key: string]: unknown;");
      }
      return properties.length ? `{\n${properties.join("\n")}\n}` : "Record<string, never>";
    }
    default: return "unknown";
  }
}

export function renderTypeScript(surface: ToolSurface): string {
  const interfaces = surface.tools.map((tool) => {
    const body = schemaType(tool.inputSchema);
    const declaration = body.startsWith("{") ? `export interface ${pascal(tool.name)}Params ${body}`
      : `export type ${pascal(tool.name)}Params = ${body};`;
    return `${jsdoc(tool.description)}\n${declaration}`;
  }).join("\n\n");
  const methods = surface.tools.map((tool) =>
    `  ${propertyName(tool.socketMethod)}(params: ${pascal(tool.name)}Params): Promise<Record<string, unknown>>;`
  ).join("\n");
  const availability = Object.fromEntries(surface.tools.map((tool) => [tool.socketMethod, tool.availability]));
  return `// Generated by sdk/generate.ts from schema/tool-surface-v1.json. Do not edit.\n\n` +
    `export const schemaProductVersion = ${JSON.stringify(surface.productVersion)} as const;\n\n` +
    `export const availability = ${JSON.stringify(availability, null, 2)} as const;\n\n` +
    `${interfaces}\n\nexport interface RawClient {\n${methods}\n}\n`;
}